### PR TITLE
Trigger support - Not working

### PR DESCRIPTION
**Pull request by eldadts**
Testing trigger support.

Issue to solve - create triggers while table is locked.

### CODE REVIEW

**Comment by eldadts** [comment]
@shlomi-noach , as I mentioned in the mail
I have tried the approach of completely migrating the triggers (i.e dropping from source table, creating with the same name on gh-ost table), but I had issues with rolling back in case of a failure; when trying to recreate the triggers on the source again (using the same Tx as the magictable lock, or using a different session) - seems like it wont create triggers while the table is locked (which should work).


So trying a different approach - migrating the triggers after the rename and use a dedicate lock->drop trigger->create trigger->unlock - Also got blocked here because table is locked and gh-ost gets stuck.

Whats working for now is the creation of triggers on the gh-ost table with the suffix "_gho".


The problematic function: https://github.com/openark/gh-ost/pull/29/commits/5fe0cb37cf57f3584d3e756b900c8d7d49e6fa8d#diff-fb019189debe458585c9fdbb9c1f9019106b03891dd430152457409c9ae44ddfR319

**Comment by shlomi-noach** [comment]
I'm not sure I have a good answer re: locking. Matedata locking in MySQL is always complicated and unexpected, and needs to be investigated per use case.

However, I wonder: do you really need to drop triggers on the original table? Consider:

- While migrating, triggers exist as usual on the original table, and no triggers on ghost table.
- At time of cutover, when original table is locked, you create triggers on ghost table.
- Assuming cut-over is successful, original table is renamed as "old" table -- along with its trigger. But no one will ever `INSERT` or `DELETE` from that table, so it's OK to keep the triggers for a while.
  - After cut-over is complete you can drop those old triggers
- Assuming cut-over has failed, you only need to drop the triggers from the ghost table.

What do you think?

**Comment by eldadts** [comment]
Hi Shlomi,
That was what I originally did - but then came the question of keeping the original trigger name (for the sake of OSS)
If no, then that plan is easy enough.
If yes - its a pickel!

**Comment by shlomi-noach** [comment]
> but then came the question of keeping the original trigger name (for the sake of OSS)

That's a good point and I appreciate that you gave this consideration. I think we can tolerate a new name for the triggers, as long as this is documented. This is in line with how `pt-online-schema-change` gives a new name for foreign keys.

So let's do that for now.

**Pull request closed without merging**
